### ISSUE TITLE
problems installing: No rule to make target 'node_modules/promise-polyfill/promise.js'

### ISSUE THREAD

**Issue by ddreyer** [evervault/node-secureworker#12]
Running npm install and I get the following error: make: *** No rule to make target 'node_modules/promise-polyfill/promise.js', needed by 'enclave-autoexec/autoexec.js'.  Stop.
Any suggestions on how to fix this?

**Comment by wh0** [comment]
Do you maybe have a later version of promise-polyfill where the file names have changed?

**Comment by ddreyer** [comment]
not sure, but promise.js definitely exists

**Comment by Isan-Rivkin** [comment]
Same issue
